site_name: Agent Evaluation
copyright: Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    annotation: material/plus-circle-outline
    repo: material/github
  logo: logo.png
  favicon: favicon.svg
  font:
    text: Inter
    code:  Roboto Mono
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: "Switch to light mode"
  features:
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tabs
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - Configuration:
    - configuration.md
    - Evaluators:
      - evaluators/index.md
    - Targets:
      - targets/index.md
      - targets/bedrock_agents.md
      - targets/bedrock_knowledge_bases.md
      - targets/q_business.md
      - targets/sagemaker_endpoints.md
      - targets/weni.md
      - targets/custom_targets.md
    - Hooks: hooks.md
  - CLI: cli.md
  - CI/CD: cicd/index.md
  - Reference:
    - BaseTarget: reference/base_target.md
    - Hook: reference/hook.md
    - TargetResponse: reference/target_response.md
    - Test: reference/test.md
    - TestResult: reference/test_result.md
    - Trace: reference/trace.md
repo_url: https://github.com/awslabs/agent-evaluation
repo_name: awslabs/agent-evaluation
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - mkdocs-click
extra:
  analytics:
    provider: google
    property: G-KEHF0ES7XR
extra_css:
  - stylesheets/extra.css
plugins:
- search
- mkdocstrings
